import Head from 'next/head'
import Banner from '../components/Banner'
import Component2 from '../components/Component2'
import Component3 from '../components/Component3'
import Component4 from '../components/Component4'
import Component5 from '../components/Component5'
import Component6 from '../components/Component6'
import Component7 from '../components/Component7'
import Component8 from '../components/Component8'
import Component9 from '../components/Component9'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MemoryVault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.layout}>
        <Banner />
        <Component3 />
        <Component2 />
        <Component4 />
        <Component5 />
        <Component6 />
        <Component8 />
        <Component7 />
        <Component9 />
      </main>

      <footer className={styles.footer}>
        <p>MemonryVault  |  Contact : +91 8885585495  |  India</p>
      </footer>
    </div>
  )
}
